import type { PresetThemeId, ThemeId, ThemeTokens } from '../types/theme';

export const windowsXpTheme: ThemeTokens = {
  id: 'windows-xp',
  name: 'Windows XP',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #0078D7, #005A9E)',
      foreground: '#FFFFFF',
      height: 30,
      font: '12px Segoe UI, sans-serif',
      borderRadius: '0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #333333',
    borderRadius: '0',
    shadow: '0 2px 10px rgba(0,0,0,0.2)',
  },
  form: {
    backgroundColor: '#F0F0F0',
    foreground: '#000000',
    fontFamily: 'Segoe UI, Tahoma, sans-serif',
    fontSize: '12px',
  },
  controls: {
    button: {
      background: '#E1E1E1',
      border: '1px outset #D0D0D0',
      borderRadius: '0',
      foreground: '#000000',
      hoverBackground: '#D0D0D0',
      padding: '2px 8px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px inset #A0A0A0',
      borderRadius: '0',
      foreground: '#000000',
      focusBorder: '1px inset #0078D7',
      padding: '2px 4px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px inset #A0A0A0',
      borderRadius: '0',
      foreground: '#000000',
      selectedBackground: '#0078D7',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #999999',
      background: '#FFFFFF',
      checkedBackground: '#0078D7',
      borderRadius: '0',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #999999',
      borderRadius: '0',
    },
    groupBox: {
      border: '1px solid #D0D0D0',
      borderRadius: '0',
      foreground: '#000000',
    },
    tabControl: {
      tabBackground: '#F0F0F0',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #A0A0A0',
      tabBorderRadius: '0',
      tabForeground: '#000000',
      tabActiveForeground: '#000000',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #A0A0A0',
    },
    dataGrid: {
      headerBackground: '#E8E8E8',
      headerForeground: '#000000',
      headerBorder: '1px solid #C0C0C0',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#F5F5F5',
      rowForeground: '#000000',
      border: '1px solid #A0A0A0',
      borderRadius: '0',
      selectedRowBackground: '#0078D7',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#E0E0E0',
      fillBackground: '#06B025',
      border: '1px solid #A0A0A0',
      borderRadius: '0',
    },
    menuStrip: {
      background: '#F0F0F0',
      foreground: '#000000',
      border: '1px solid #D0D0D0',
      hoverBackground: '#D0E8FF',
      hoverForeground: '#000000',
      activeBackground: '#CCE4FF',
    },
    toolStrip: {
      background: '#F0F0F0',
      foreground: '#000000',
      border: '1px solid #D0D0D0',
      buttonHoverBackground: '#D0E8FF',
      separator: '#C0C0C0',
    },
    statusStrip: {
      background: '#F0F0F0',
      foreground: '#444444',
      border: '1px solid #D0D0D0',
    },
    scrollbar: {
      trackBackground: '#F0F0F0',
      thumbBackground: '#C0C0C0',
      thumbHoverBackground: '#A0A0A0',
      width: 17,
    },
  },
  accent: {
    primary: '#0078D7',
    primaryHover: '#005A9E',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #999999',
    shadow: '2px 2px 6px rgba(0,0,0,0.2)',
    borderRadius: '0',
    hoverBackground: '#D0E8FF',
  },
};

export const ubuntu2004Theme: ThemeTokens = {
  id: 'ubuntu-2004',
  name: 'Ubuntu 20.04',
  window: {
    titleBar: {
      background: '#3C3C3C',
      foreground: '#FFFFFF',
      height: 36,
      font: '13px Ubuntu, "Noto Sans", sans-serif',
      borderRadius: '10px 10px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #2C2C2C',
    borderRadius: '10px',
    shadow: '0 4px 16px rgba(0,0,0,0.3)',
  },
  form: {
    backgroundColor: '#F6F5F4',
    foreground: '#3D3846',
    fontFamily: 'Ubuntu, "Noto Sans", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#FFFFFF',
      border: '1px solid #CDCDC9',
      borderRadius: '5px',
      foreground: '#3D3846',
      hoverBackground: '#F0EFED',
      padding: '4px 16px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #CDCDC9',
      borderRadius: '5px',
      foreground: '#3D3846',
      focusBorder: '1px solid #E95420',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #CDCDC9',
      borderRadius: '5px',
      foreground: '#3D3846',
      selectedBackground: '#E95420',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #CDCDC9',
      background: '#FFFFFF',
      checkedBackground: '#E95420',
      borderRadius: '3px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #CDCDC9',
      borderRadius: '8px',
    },
    groupBox: {
      border: '1px solid #CDCDC9',
      borderRadius: '8px',
      foreground: '#3D3846',
    },
    tabControl: {
      tabBackground: '#E8E7E5',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #CDCDC9',
      tabBorderRadius: '8px 8px 0 0',
      tabForeground: '#77767B',
      tabActiveForeground: '#3D3846',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #CDCDC9',
    },
    dataGrid: {
      headerBackground: '#E8E7E5',
      headerForeground: '#3D3846',
      headerBorder: '1px solid #CDCDC9',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#F8F7F6',
      rowForeground: '#3D3846',
      border: '1px solid #CDCDC9',
      borderRadius: '8px',
      selectedRowBackground: '#E95420',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#E8E7E5',
      fillBackground: '#E95420',
      border: '1px solid #CDCDC9',
      borderRadius: '5px',
    },
    menuStrip: {
      background: '#3C3C3C',
      foreground: '#FFFFFF',
      border: 'none',
      hoverBackground: '#505050',
      hoverForeground: '#FFFFFF',
      activeBackground: '#E95420',
    },
    toolStrip: {
      background: '#F6F5F4',
      foreground: '#3D3846',
      border: '1px solid #CDCDC9',
      buttonHoverBackground: '#E8E7E5',
      separator: '#CDCDC9',
    },
    statusStrip: {
      background: '#F6F5F4',
      foreground: '#77767B',
      border: '1px solid #CDCDC9',
    },
    scrollbar: {
      trackBackground: 'transparent',
      thumbBackground: '#C0BFBC',
      thumbHoverBackground: '#9A9996',
      width: 8,
    },
  },
  accent: {
    primary: '#E95420',
    primaryHover: '#C7431A',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #CDCDC9',
    shadow: '0 4px 12px rgba(0,0,0,0.15)',
    borderRadius: '8px',
    hoverBackground: '#F0EFED',
  },
};

export const macosTahoeTheme: ThemeTokens = {
  id: 'macos-tahoe',
  name: 'macOS Tahoe',
  window: {
    titleBar: {
      background: 'linear-gradient(to bottom, #ECECEC, #E0E0E0)',
      foreground: '#333333',
      height: 28,
      font: '13px -apple-system, BlinkMacSystemFont, "SF Pro", "Helvetica Neue", sans-serif',
      borderRadius: '10px 10px 0 0',
      controlButtonsPosition: 'left',
    },
    border: '1px solid rgba(0,0,0,0.12)',
    borderRadius: '10px',
    shadow: '0 8px 32px rgba(0,0,0,0.18), 0 2px 8px rgba(0,0,0,0.08)',
  },
  form: {
    backgroundColor: '#FFFFFF',
    foreground: '#1D1D1F',
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro", "Helvetica Neue", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#FFFFFF',
      border: '1px solid rgba(0,0,0,0.12)',
      borderRadius: '6px',
      foreground: '#1D1D1F',
      hoverBackground: '#F5F5F7',
      padding: '3px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid rgba(0,0,0,0.12)',
      borderRadius: '6px',
      foreground: '#1D1D1F',
      focusBorder: '2px solid #007AFF',
      padding: '3px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid rgba(0,0,0,0.12)',
      borderRadius: '6px',
      foreground: '#1D1D1F',
      selectedBackground: '#007AFF',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid rgba(0,0,0,0.2)',
      background: '#FFFFFF',
      checkedBackground: '#007AFF',
      borderRadius: '4px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid rgba(0,0,0,0.08)',
      borderRadius: '8px',
    },
    groupBox: {
      border: '1px solid rgba(0,0,0,0.1)',
      borderRadius: '8px',
      foreground: '#1D1D1F',
    },
    tabControl: {
      tabBackground: '#F5F5F7',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid rgba(0,0,0,0.1)',
      tabBorderRadius: '6px 6px 0 0',
      tabForeground: '#86868B',
      tabActiveForeground: '#1D1D1F',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid rgba(0,0,0,0.1)',
    },
    dataGrid: {
      headerBackground: '#F5F5F7',
      headerForeground: '#86868B',
      headerBorder: '1px solid rgba(0,0,0,0.08)',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#FAFAFA',
      rowForeground: '#1D1D1F',
      border: '1px solid rgba(0,0,0,0.1)',
      borderRadius: '8px',
      selectedRowBackground: '#007AFF',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#E5E5EA',
      fillBackground: '#007AFF',
      border: 'none',
      borderRadius: '4px',
    },
    menuStrip: {
      background: 'rgba(246,246,246,0.8)',
      foreground: '#1D1D1F',
      border: '1px solid rgba(0,0,0,0.06)',
      hoverBackground: 'rgba(0,122,255,0.1)',
      hoverForeground: '#1D1D1F',
      activeBackground: '#007AFF',
    },
    toolStrip: {
      background: '#F5F5F7',
      foreground: '#1D1D1F',
      border: '1px solid rgba(0,0,0,0.08)',
      buttonHoverBackground: 'rgba(0,0,0,0.05)',
      separator: 'rgba(0,0,0,0.1)',
    },
    statusStrip: {
      background: '#F5F5F7',
      foreground: '#86868B',
      border: '1px solid rgba(0,0,0,0.06)',
    },
    scrollbar: {
      trackBackground: 'transparent',
      thumbBackground: 'rgba(0,0,0,0.2)',
      thumbHoverBackground: 'rgba(0,0,0,0.4)',
      width: 8,
    },
  },
  accent: {
    primary: '#007AFF',
    primaryHover: '#005ECB',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    shadow: '0 8px 24px rgba(0,0,0,0.12), 0 2px 8px rgba(0,0,0,0.06)',
    borderRadius: '10px',
    hoverBackground: '#F5F5F7',
  },
};

export const vibrantNeonTheme: ThemeTokens = {
  id: 'vibrant-neon',
  name: 'Vibrant Neon',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #7C3AED, #DB2777)',
      foreground: '#FFFFFF',
      height: 34,
      font: '13px "Inter", "Segoe UI", sans-serif',
      borderRadius: '12px 12px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid rgba(139, 92, 246, 0.3)',
    borderRadius: '12px',
    shadow: '0 8px 32px rgba(124, 58, 237, 0.25), 0 0 16px rgba(219, 39, 119, 0.15)',
  },
  form: {
    backgroundColor: '#1A1B2E',
    foreground: '#E8E8F0',
    fontFamily: '"Inter", "Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: 'linear-gradient(135deg, #7C3AED, #9333EA)',
      border: '1px solid rgba(139, 92, 246, 0.4)',
      borderRadius: '8px',
      foreground: '#FFFFFF',
      hoverBackground: 'linear-gradient(135deg, #8B5CF6, #A855F7)',
      padding: '4px 16px',
    },
    textInput: {
      background: '#252640',
      border: '1px solid rgba(139, 92, 246, 0.3)',
      borderRadius: '8px',
      foreground: '#E8E8F0',
      focusBorder: '2px solid #A855F7',
      padding: '4px 8px',
    },
    select: {
      background: '#252640',
      border: '1px solid rgba(139, 92, 246, 0.3)',
      borderRadius: '8px',
      foreground: '#E8E8F0',
      selectedBackground: '#7C3AED',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid rgba(139, 92, 246, 0.4)',
      background: '#252640',
      checkedBackground: '#A855F7',
      borderRadius: '4px',
    },
    panel: {
      background: 'rgba(37, 38, 64, 0.6)',
      border: '1px solid rgba(139, 92, 246, 0.2)',
      borderRadius: '10px',
    },
    groupBox: {
      border: '1px solid rgba(139, 92, 246, 0.25)',
      borderRadius: '10px',
      foreground: '#C4B5FD',
    },
    tabControl: {
      tabBackground: '#1E1F33',
      tabActiveBackground: '#2D2E4A',
      tabBorder: '1px solid rgba(139, 92, 246, 0.2)',
      tabBorderRadius: '8px 8px 0 0',
      tabForeground: '#8B8BA3',
      tabActiveForeground: '#C4B5FD',
      contentBackground: '#2D2E4A',
      contentBorder: '1px solid rgba(139, 92, 246, 0.2)',
    },
    dataGrid: {
      headerBackground: '#252640',
      headerForeground: '#C4B5FD',
      headerBorder: '1px solid rgba(139, 92, 246, 0.2)',
      rowBackground: '#1E1F33',
      rowAlternateBackground: '#232442',
      rowForeground: '#E8E8F0',
      border: '1px solid rgba(139, 92, 246, 0.2)',
      borderRadius: '10px',
      selectedRowBackground: '#7C3AED',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#252640',
      fillBackground: 'linear-gradient(to right, #7C3AED, #EC4899)',
      border: '1px solid rgba(139, 92, 246, 0.2)',
      borderRadius: '6px',
    },
    menuStrip: {
      background: '#16172B',
      foreground: '#E8E8F0',
      border: '1px solid rgba(139, 92, 246, 0.15)',
      hoverBackground: 'rgba(124, 58, 237, 0.2)',
      hoverForeground: '#FFFFFF',
      activeBackground: '#7C3AED',
    },
    toolStrip: {
      background: '#1E1F33',
      foreground: '#C4B5FD',
      border: '1px solid rgba(139, 92, 246, 0.15)',
      buttonHoverBackground: 'rgba(124, 58, 237, 0.2)',
      separator: 'rgba(139, 92, 246, 0.2)',
    },
    statusStrip: {
      background: '#16172B',
      foreground: '#8B8BA3',
      border: '1px solid rgba(139, 92, 246, 0.15)',
    },
    scrollbar: {
      trackBackground: 'transparent',
      thumbBackground: 'rgba(139, 92, 246, 0.3)',
      thumbHoverBackground: 'rgba(139, 92, 246, 0.5)',
      width: 8,
    },
  },
  accent: {
    primary: '#A855F7',
    primaryHover: '#7C3AED',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#252640',
    border: '1px solid rgba(139, 92, 246, 0.3)',
    shadow: '0 8px 24px rgba(124, 58, 237, 0.2), 0 0 12px rgba(168, 85, 247, 0.1)',
    borderRadius: '10px',
    hoverBackground: 'rgba(124, 58, 237, 0.15)',
  },
};

export const arcticFrostTheme: ThemeTokens = {
  id: 'arctic-frost',
  name: 'Arctic Frost',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #B3E5FC, #E1F5FE)',
      foreground: '#01579B',
      height: 32,
      font: '13px "Segoe UI", sans-serif',
      borderRadius: '8px 8px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #B3E5FC',
    borderRadius: '8px',
    shadow: '0 4px 16px rgba(1, 87, 155, 0.1)',
  },
  form: {
    backgroundColor: '#F8FDFF',
    foreground: '#1A3A4A',
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#E1F5FE',
      border: '1px solid #81D4FA',
      borderRadius: '6px',
      foreground: '#01579B',
      hoverBackground: '#B3E5FC',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #B3E5FC',
      borderRadius: '6px',
      foreground: '#1A3A4A',
      focusBorder: '2px solid #4FC3F7',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #B3E5FC',
      borderRadius: '6px',
      foreground: '#1A3A4A',
      selectedBackground: '#4FC3F7',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #81D4FA',
      background: '#FFFFFF',
      checkedBackground: '#4FC3F7',
      borderRadius: '4px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #B3E5FC',
      borderRadius: '8px',
    },
    groupBox: {
      border: '1px solid #B3E5FC',
      borderRadius: '8px',
      foreground: '#01579B',
    },
    tabControl: {
      tabBackground: '#E1F5FE',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #B3E5FC',
      tabBorderRadius: '6px 6px 0 0',
      tabForeground: '#4889A0',
      tabActiveForeground: '#01579B',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #B3E5FC',
    },
    dataGrid: {
      headerBackground: '#E1F5FE',
      headerForeground: '#01579B',
      headerBorder: '1px solid #B3E5FC',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#F0FAFF',
      rowForeground: '#1A3A4A',
      border: '1px solid #B3E5FC',
      borderRadius: '8px',
      selectedRowBackground: '#4FC3F7',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#E1F5FE',
      fillBackground: '#4FC3F7',
      border: '1px solid #B3E5FC',
      borderRadius: '4px',
    },
    menuStrip: {
      background: '#E1F5FE',
      foreground: '#01579B',
      border: '1px solid #B3E5FC',
      hoverBackground: '#B3E5FC',
      hoverForeground: '#01579B',
      activeBackground: '#4FC3F7',
    },
    toolStrip: {
      background: '#E1F5FE',
      foreground: '#01579B',
      border: '1px solid #B3E5FC',
      buttonHoverBackground: '#B3E5FC',
      separator: '#81D4FA',
    },
    statusStrip: {
      background: '#E1F5FE',
      foreground: '#4889A0',
      border: '1px solid #B3E5FC',
    },
    scrollbar: {
      trackBackground: '#F0FAFF',
      thumbBackground: '#81D4FA',
      thumbHoverBackground: '#4FC3F7',
      width: 8,
    },
  },
  accent: {
    primary: '#4FC3F7',
    primaryHover: '#039BE5',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #B3E5FC',
    shadow: '0 4px 12px rgba(1, 87, 155, 0.1)',
    borderRadius: '8px',
    hoverBackground: '#E1F5FE',
  },
};

export const autumnHarvestTheme: ThemeTokens = {
  id: 'autumn-harvest',
  name: 'Autumn Harvest',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #BF360C, #E65100)',
      foreground: '#FFFFFF',
      height: 32,
      font: '13px "Segoe UI", Georgia, sans-serif',
      borderRadius: '6px 6px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #BF360C',
    borderRadius: '6px',
    shadow: '0 4px 16px rgba(191, 54, 12, 0.2)',
  },
  form: {
    backgroundColor: '#FFF8F0',
    foreground: '#3E2723',
    fontFamily: '"Segoe UI", Georgia, sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#FFECB3',
      border: '1px solid #FFB74D',
      borderRadius: '4px',
      foreground: '#3E2723',
      hoverBackground: '#FFE0B2',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #FFCC80',
      borderRadius: '4px',
      foreground: '#3E2723',
      focusBorder: '2px solid #E65100',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #FFCC80',
      borderRadius: '4px',
      foreground: '#3E2723',
      selectedBackground: '#E65100',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #FFCC80',
      background: '#FFFFFF',
      checkedBackground: '#E65100',
      borderRadius: '3px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #FFCC80',
      borderRadius: '6px',
    },
    groupBox: {
      border: '1px solid #FFCC80',
      borderRadius: '6px',
      foreground: '#BF360C',
    },
    tabControl: {
      tabBackground: '#FFF3E0',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #FFCC80',
      tabBorderRadius: '6px 6px 0 0',
      tabForeground: '#8D6E63',
      tabActiveForeground: '#3E2723',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #FFCC80',
    },
    dataGrid: {
      headerBackground: '#FFF3E0',
      headerForeground: '#BF360C',
      headerBorder: '1px solid #FFCC80',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#FFF8F0',
      rowForeground: '#3E2723',
      border: '1px solid #FFCC80',
      borderRadius: '6px',
      selectedRowBackground: '#E65100',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#FFF3E0',
      fillBackground: 'linear-gradient(to right, #E65100, #FF8F00)',
      border: '1px solid #FFCC80',
      borderRadius: '4px',
    },
    menuStrip: {
      background: '#FFF3E0',
      foreground: '#3E2723',
      border: '1px solid #FFCC80',
      hoverBackground: '#FFE0B2',
      hoverForeground: '#3E2723',
      activeBackground: '#E65100',
    },
    toolStrip: {
      background: '#FFF3E0',
      foreground: '#3E2723',
      border: '1px solid #FFCC80',
      buttonHoverBackground: '#FFE0B2',
      separator: '#FFCC80',
    },
    statusStrip: {
      background: '#FFF3E0',
      foreground: '#8D6E63',
      border: '1px solid #FFCC80',
    },
    scrollbar: {
      trackBackground: '#FFF8F0',
      thumbBackground: '#FFCC80',
      thumbHoverBackground: '#FFB74D',
      width: 10,
    },
  },
  accent: {
    primary: '#E65100',
    primaryHover: '#BF360C',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #FFCC80',
    shadow: '0 4px 12px rgba(191, 54, 12, 0.15)',
    borderRadius: '6px',
    hoverBackground: '#FFF3E0',
  },
};

export const cherryBlossomTheme: ThemeTokens = {
  id: 'cherry-blossom',
  name: 'Cherry Blossom',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #F48FB1, #F8BBD0)',
      foreground: '#880E4F',
      height: 32,
      font: '13px "Segoe UI", sans-serif',
      borderRadius: '10px 10px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #F48FB1',
    borderRadius: '10px',
    shadow: '0 4px 16px rgba(236, 64, 122, 0.15)',
  },
  form: {
    backgroundColor: '#FFF0F5',
    foreground: '#4A0E2A',
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#FCE4EC',
      border: '1px solid #F48FB1',
      borderRadius: '8px',
      foreground: '#880E4F',
      hoverBackground: '#F8BBD0',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #F48FB1',
      borderRadius: '8px',
      foreground: '#4A0E2A',
      focusBorder: '2px solid #EC407A',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #F48FB1',
      borderRadius: '8px',
      foreground: '#4A0E2A',
      selectedBackground: '#EC407A',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #F48FB1',
      background: '#FFFFFF',
      checkedBackground: '#EC407A',
      borderRadius: '4px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #F8BBD0',
      borderRadius: '10px',
    },
    groupBox: {
      border: '1px solid #F8BBD0',
      borderRadius: '10px',
      foreground: '#880E4F',
    },
    tabControl: {
      tabBackground: '#FCE4EC',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #F8BBD0',
      tabBorderRadius: '8px 8px 0 0',
      tabForeground: '#C2185B',
      tabActiveForeground: '#880E4F',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #F8BBD0',
    },
    dataGrid: {
      headerBackground: '#FCE4EC',
      headerForeground: '#880E4F',
      headerBorder: '1px solid #F8BBD0',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#FFF0F5',
      rowForeground: '#4A0E2A',
      border: '1px solid #F8BBD0',
      borderRadius: '10px',
      selectedRowBackground: '#EC407A',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#FCE4EC',
      fillBackground: 'linear-gradient(to right, #EC407A, #F48FB1)',
      border: '1px solid #F8BBD0',
      borderRadius: '6px',
    },
    menuStrip: {
      background: '#FCE4EC',
      foreground: '#880E4F',
      border: '1px solid #F8BBD0',
      hoverBackground: '#F8BBD0',
      hoverForeground: '#880E4F',
      activeBackground: '#EC407A',
    },
    toolStrip: {
      background: '#FCE4EC',
      foreground: '#880E4F',
      border: '1px solid #F8BBD0',
      buttonHoverBackground: '#F8BBD0',
      separator: '#F48FB1',
    },
    statusStrip: {
      background: '#FCE4EC',
      foreground: '#C2185B',
      border: '1px solid #F8BBD0',
    },
    scrollbar: {
      trackBackground: '#FFF0F5',
      thumbBackground: '#F48FB1',
      thumbHoverBackground: '#EC407A',
      width: 8,
    },
  },
  accent: {
    primary: '#EC407A',
    primaryHover: '#C2185B',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #F8BBD0',
    shadow: '0 4px 12px rgba(236, 64, 122, 0.12)',
    borderRadius: '10px',
    hoverBackground: '#FCE4EC',
  },
};

export const darkMonokaiTheme: ThemeTokens = {
  id: 'dark-monokai',
  name: 'Dark Monokai',
  window: {
    titleBar: {
      background: '#1E1F1C',
      foreground: '#F8F8F2',
      height: 32,
      font: '13px "Consolas", "Courier New", monospace',
      borderRadius: '4px 4px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #3E3D32',
    borderRadius: '4px',
    shadow: '0 4px 16px rgba(0, 0, 0, 0.4)',
  },
  form: {
    backgroundColor: '#272822',
    foreground: '#F8F8F2',
    fontFamily: '"Consolas", "Courier New", monospace',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#3E3D32',
      border: '1px solid #49483E',
      borderRadius: '3px',
      foreground: '#F8F8F2',
      hoverBackground: '#49483E',
      padding: '4px 12px',
    },
    textInput: {
      background: '#1E1F1C',
      border: '1px solid #49483E',
      borderRadius: '3px',
      foreground: '#F8F8F2',
      focusBorder: '2px solid #A6E22E',
      padding: '4px 8px',
    },
    select: {
      background: '#1E1F1C',
      border: '1px solid #49483E',
      borderRadius: '3px',
      foreground: '#F8F8F2',
      selectedBackground: '#49483E',
      selectedForeground: '#A6E22E',
    },
    checkRadio: {
      border: '1px solid #49483E',
      background: '#1E1F1C',
      checkedBackground: '#A6E22E',
      borderRadius: '2px',
    },
    panel: {
      background: 'rgba(30, 31, 28, 0.6)',
      border: '1px solid #3E3D32',
      borderRadius: '4px',
    },
    groupBox: {
      border: '1px solid #3E3D32',
      borderRadius: '4px',
      foreground: '#E6DB74',
    },
    tabControl: {
      tabBackground: '#1E1F1C',
      tabActiveBackground: '#272822',
      tabBorder: '1px solid #3E3D32',
      tabBorderRadius: '4px 4px 0 0',
      tabForeground: '#75715E',
      tabActiveForeground: '#F8F8F2',
      contentBackground: '#272822',
      contentBorder: '1px solid #3E3D32',
    },
    dataGrid: {
      headerBackground: '#3E3D32',
      headerForeground: '#E6DB74',
      headerBorder: '1px solid #49483E',
      rowBackground: '#272822',
      rowAlternateBackground: '#2D2E27',
      rowForeground: '#F8F8F2',
      border: '1px solid #3E3D32',
      borderRadius: '4px',
      selectedRowBackground: '#49483E',
      selectedRowForeground: '#A6E22E',
    },
    progressBar: {
      background: '#3E3D32',
      fillBackground: '#A6E22E',
      border: '1px solid #49483E',
      borderRadius: '2px',
    },
    menuStrip: {
      background: '#1E1F1C',
      foreground: '#F8F8F2',
      border: '1px solid #3E3D32',
      hoverBackground: '#3E3D32',
      hoverForeground: '#F8F8F2',
      activeBackground: '#49483E',
    },
    toolStrip: {
      background: '#1E1F1C',
      foreground: '#F8F8F2',
      border: '1px solid #3E3D32',
      buttonHoverBackground: '#3E3D32',
      separator: '#49483E',
    },
    statusStrip: {
      background: '#1E1F1C',
      foreground: '#75715E',
      border: '1px solid #3E3D32',
    },
    scrollbar: {
      trackBackground: '#272822',
      thumbBackground: '#49483E',
      thumbHoverBackground: '#75715E',
      width: 10,
    },
  },
  accent: {
    primary: '#A6E22E',
    primaryHover: '#8CC219',
    primaryForeground: '#272822',
  },
  popup: {
    background: '#272822',
    border: '1px solid #49483E',
    shadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
    borderRadius: '4px',
    hoverBackground: '#3E3D32',
  },
};

export const forestGreenTheme: ThemeTokens = {
  id: 'forest-green',
  name: 'Forest Green',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #1B5E20, #2E7D32)',
      foreground: '#FFFFFF',
      height: 32,
      font: '13px "Segoe UI", sans-serif',
      borderRadius: '6px 6px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #1B5E20',
    borderRadius: '6px',
    shadow: '0 4px 16px rgba(27, 94, 32, 0.2)',
  },
  form: {
    backgroundColor: '#F1F8E9',
    foreground: '#1B3A1B',
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#DCEDC8',
      border: '1px solid #A5D6A7',
      borderRadius: '5px',
      foreground: '#1B5E20',
      hoverBackground: '#C5E1A5',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #A5D6A7',
      borderRadius: '5px',
      foreground: '#1B3A1B',
      focusBorder: '2px solid #2E7D32',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #A5D6A7',
      borderRadius: '5px',
      foreground: '#1B3A1B',
      selectedBackground: '#2E7D32',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #A5D6A7',
      background: '#FFFFFF',
      checkedBackground: '#2E7D32',
      borderRadius: '3px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #C5E1A5',
      borderRadius: '6px',
    },
    groupBox: {
      border: '1px solid #C5E1A5',
      borderRadius: '6px',
      foreground: '#1B5E20',
    },
    tabControl: {
      tabBackground: '#DCEDC8',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #C5E1A5',
      tabBorderRadius: '6px 6px 0 0',
      tabForeground: '#558B2F',
      tabActiveForeground: '#1B5E20',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #C5E1A5',
    },
    dataGrid: {
      headerBackground: '#DCEDC8',
      headerForeground: '#1B5E20',
      headerBorder: '1px solid #C5E1A5',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#F1F8E9',
      rowForeground: '#1B3A1B',
      border: '1px solid #C5E1A5',
      borderRadius: '6px',
      selectedRowBackground: '#2E7D32',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#DCEDC8',
      fillBackground: '#2E7D32',
      border: '1px solid #C5E1A5',
      borderRadius: '4px',
    },
    menuStrip: {
      background: '#DCEDC8',
      foreground: '#1B5E20',
      border: '1px solid #C5E1A5',
      hoverBackground: '#C5E1A5',
      hoverForeground: '#1B5E20',
      activeBackground: '#2E7D32',
    },
    toolStrip: {
      background: '#DCEDC8',
      foreground: '#1B5E20',
      border: '1px solid #C5E1A5',
      buttonHoverBackground: '#C5E1A5',
      separator: '#A5D6A7',
    },
    statusStrip: {
      background: '#DCEDC8',
      foreground: '#558B2F',
      border: '1px solid #C5E1A5',
    },
    scrollbar: {
      trackBackground: '#F1F8E9',
      thumbBackground: '#A5D6A7',
      thumbHoverBackground: '#66BB6A',
      width: 10,
    },
  },
  accent: {
    primary: '#2E7D32',
    primaryHover: '#1B5E20',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #C5E1A5',
    shadow: '0 4px 12px rgba(27, 94, 32, 0.12)',
    borderRadius: '6px',
    hoverBackground: '#DCEDC8',
  },
};

export const materialBlueTheme: ThemeTokens = {
  id: 'material-blue',
  name: 'Material Blue',
  window: {
    titleBar: {
      background: '#1976D2',
      foreground: '#FFFFFF',
      height: 34,
      font: '14px "Roboto", "Segoe UI", sans-serif',
      borderRadius: '4px 4px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #1565C0',
    borderRadius: '4px',
    shadow: '0 2px 4px rgba(0,0,0,0.14), 0 4px 8px rgba(0,0,0,0.12)',
  },
  form: {
    backgroundColor: '#FAFAFA',
    foreground: '#212121',
    fontFamily: '"Roboto", "Segoe UI", sans-serif',
    fontSize: '14px',
  },
  controls: {
    button: {
      background: '#1976D2',
      border: 'none',
      borderRadius: '4px',
      foreground: '#FFFFFF',
      hoverBackground: '#1565C0',
      padding: '6px 16px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #BDBDBD',
      borderRadius: '4px',
      foreground: '#212121',
      focusBorder: '2px solid #1976D2',
      padding: '6px 12px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #BDBDBD',
      borderRadius: '4px',
      foreground: '#212121',
      selectedBackground: '#1976D2',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '2px solid #757575',
      background: '#FFFFFF',
      checkedBackground: '#1976D2',
      borderRadius: '2px',
    },
    panel: {
      background: '#FFFFFF',
      border: 'none',
      borderRadius: '4px',
    },
    groupBox: {
      border: '1px solid #E0E0E0',
      borderRadius: '4px',
      foreground: '#1976D2',
    },
    tabControl: {
      tabBackground: '#FAFAFA',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #E0E0E0',
      tabBorderRadius: '4px 4px 0 0',
      tabForeground: '#757575',
      tabActiveForeground: '#1976D2',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #E0E0E0',
    },
    dataGrid: {
      headerBackground: '#F5F5F5',
      headerForeground: '#757575',
      headerBorder: '1px solid #E0E0E0',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#FAFAFA',
      rowForeground: '#212121',
      border: '1px solid #E0E0E0',
      borderRadius: '4px',
      selectedRowBackground: '#BBDEFB',
      selectedRowForeground: '#212121',
    },
    progressBar: {
      background: '#E3F2FD',
      fillBackground: '#1976D2',
      border: 'none',
      borderRadius: '2px',
    },
    menuStrip: {
      background: '#1976D2',
      foreground: '#FFFFFF',
      border: 'none',
      hoverBackground: 'rgba(255,255,255,0.1)',
      hoverForeground: '#FFFFFF',
      activeBackground: '#1565C0',
    },
    toolStrip: {
      background: '#FAFAFA',
      foreground: '#212121',
      border: '1px solid #E0E0E0',
      buttonHoverBackground: '#F5F5F5',
      separator: '#E0E0E0',
    },
    statusStrip: {
      background: '#FAFAFA',
      foreground: '#757575',
      border: '1px solid #E0E0E0',
    },
    scrollbar: {
      trackBackground: 'transparent',
      thumbBackground: '#BDBDBD',
      thumbHoverBackground: '#9E9E9E',
      width: 8,
    },
  },
  accent: {
    primary: '#1976D2',
    primaryHover: '#1565C0',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #E0E0E0',
    shadow: '0 8px 16px rgba(0,0,0,0.14), 0 2px 4px rgba(0,0,0,0.12)',
    borderRadius: '4px',
    hoverBackground: '#F5F5F5',
  },
};

export const oceanBreezeTheme: ThemeTokens = {
  id: 'ocean-breeze',
  name: 'Ocean Breeze',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #00695C, #00897B)',
      foreground: '#FFFFFF',
      height: 32,
      font: '13px "Segoe UI", sans-serif',
      borderRadius: '8px 8px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #00695C',
    borderRadius: '8px',
    shadow: '0 4px 16px rgba(0, 105, 92, 0.2)',
  },
  form: {
    backgroundColor: '#E0F2F1',
    foreground: '#1A3C38',
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#B2DFDB',
      border: '1px solid #80CBC4',
      borderRadius: '6px',
      foreground: '#00695C',
      hoverBackground: '#80CBC4',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FFFFFF',
      border: '1px solid #80CBC4',
      borderRadius: '6px',
      foreground: '#1A3C38',
      focusBorder: '2px solid #00897B',
      padding: '4px 8px',
    },
    select: {
      background: '#FFFFFF',
      border: '1px solid #80CBC4',
      borderRadius: '6px',
      foreground: '#1A3C38',
      selectedBackground: '#00897B',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid #80CBC4',
      background: '#FFFFFF',
      checkedBackground: '#00897B',
      borderRadius: '4px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #B2DFDB',
      borderRadius: '8px',
    },
    groupBox: {
      border: '1px solid #B2DFDB',
      borderRadius: '8px',
      foreground: '#00695C',
    },
    tabControl: {
      tabBackground: '#B2DFDB',
      tabActiveBackground: '#FFFFFF',
      tabBorder: '1px solid #80CBC4',
      tabBorderRadius: '6px 6px 0 0',
      tabForeground: '#4DB6AC',
      tabActiveForeground: '#00695C',
      contentBackground: '#FFFFFF',
      contentBorder: '1px solid #B2DFDB',
    },
    dataGrid: {
      headerBackground: '#B2DFDB',
      headerForeground: '#00695C',
      headerBorder: '1px solid #80CBC4',
      rowBackground: '#FFFFFF',
      rowAlternateBackground: '#E0F2F1',
      rowForeground: '#1A3C38',
      border: '1px solid #B2DFDB',
      borderRadius: '8px',
      selectedRowBackground: '#00897B',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#B2DFDB',
      fillBackground: '#00897B',
      border: '1px solid #80CBC4',
      borderRadius: '4px',
    },
    menuStrip: {
      background: '#B2DFDB',
      foreground: '#00695C',
      border: '1px solid #80CBC4',
      hoverBackground: '#80CBC4',
      hoverForeground: '#00695C',
      activeBackground: '#00897B',
    },
    toolStrip: {
      background: '#B2DFDB',
      foreground: '#00695C',
      border: '1px solid #80CBC4',
      buttonHoverBackground: '#80CBC4',
      separator: '#4DB6AC',
    },
    statusStrip: {
      background: '#B2DFDB',
      foreground: '#4DB6AC',
      border: '1px solid #80CBC4',
    },
    scrollbar: {
      trackBackground: '#E0F2F1',
      thumbBackground: '#80CBC4',
      thumbHoverBackground: '#4DB6AC',
      width: 8,
    },
  },
  accent: {
    primary: '#00897B',
    primaryHover: '#00695C',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#FFFFFF',
    border: '1px solid #B2DFDB',
    shadow: '0 4px 12px rgba(0, 105, 92, 0.12)',
    borderRadius: '8px',
    hoverBackground: '#E0F2F1',
  },
};

export const retroTerminalTheme: ThemeTokens = {
  id: 'retro-terminal',
  name: 'Retro Terminal',
  window: {
    titleBar: {
      background: '#0A0A0A',
      foreground: '#00FF41',
      height: 28,
      font: '13px "Courier New", "Consolas", monospace',
      borderRadius: '0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #00FF41',
    borderRadius: '0',
    shadow: '0 0 20px rgba(0, 255, 65, 0.15)',
  },
  form: {
    backgroundColor: '#0D0D0D',
    foreground: '#00FF41',
    fontFamily: '"Courier New", "Consolas", monospace',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#0A0A0A',
      border: '1px solid #00FF41',
      borderRadius: '0',
      foreground: '#00FF41',
      hoverBackground: '#1A3A1A',
      padding: '4px 12px',
    },
    textInput: {
      background: '#0A0A0A',
      border: '1px solid #00CC33',
      borderRadius: '0',
      foreground: '#00FF41',
      focusBorder: '1px solid #00FF41',
      padding: '4px 8px',
    },
    select: {
      background: '#0A0A0A',
      border: '1px solid #00CC33',
      borderRadius: '0',
      foreground: '#00FF41',
      selectedBackground: '#00CC33',
      selectedForeground: '#0D0D0D',
    },
    checkRadio: {
      border: '1px solid #00CC33',
      background: '#0A0A0A',
      checkedBackground: '#00FF41',
      borderRadius: '0',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #00CC33',
      borderRadius: '0',
    },
    groupBox: {
      border: '1px solid #00CC33',
      borderRadius: '0',
      foreground: '#00FF41',
    },
    tabControl: {
      tabBackground: '#0A0A0A',
      tabActiveBackground: '#1A2A1A',
      tabBorder: '1px solid #00CC33',
      tabBorderRadius: '0',
      tabForeground: '#00882A',
      tabActiveForeground: '#00FF41',
      contentBackground: '#0D0D0D',
      contentBorder: '1px solid #00CC33',
    },
    dataGrid: {
      headerBackground: '#0A0A0A',
      headerForeground: '#00FF41',
      headerBorder: '1px solid #00CC33',
      rowBackground: '#0D0D0D',
      rowAlternateBackground: '#111111',
      rowForeground: '#00FF41',
      border: '1px solid #00CC33',
      borderRadius: '0',
      selectedRowBackground: '#00CC33',
      selectedRowForeground: '#0D0D0D',
    },
    progressBar: {
      background: '#0A0A0A',
      fillBackground: '#00FF41',
      border: '1px solid #00CC33',
      borderRadius: '0',
    },
    menuStrip: {
      background: '#0A0A0A',
      foreground: '#00FF41',
      border: '1px solid #00CC33',
      hoverBackground: '#1A3A1A',
      hoverForeground: '#00FF41',
      activeBackground: '#00CC33',
    },
    toolStrip: {
      background: '#0A0A0A',
      foreground: '#00FF41',
      border: '1px solid #00CC33',
      buttonHoverBackground: '#1A3A1A',
      separator: '#00882A',
    },
    statusStrip: {
      background: '#0A0A0A',
      foreground: '#00882A',
      border: '1px solid #00CC33',
    },
    scrollbar: {
      trackBackground: '#0D0D0D',
      thumbBackground: '#00882A',
      thumbHoverBackground: '#00CC33',
      width: 10,
    },
  },
  accent: {
    primary: '#00FF41',
    primaryHover: '#00CC33',
    primaryForeground: '#0D0D0D',
  },
  popup: {
    background: '#0D0D0D',
    border: '1px solid #00FF41',
    shadow: '0 0 12px rgba(0, 255, 65, 0.2)',
    borderRadius: '0',
    hoverBackground: '#1A3A1A',
  },
};

export const solarizedLightTheme: ThemeTokens = {
  id: 'solarized-light',
  name: 'Solarized Light',
  window: {
    titleBar: {
      background: '#EEE8D5',
      foreground: '#586E75',
      height: 30,
      font: '13px "Consolas", "DejaVu Sans Mono", monospace',
      borderRadius: '4px 4px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid #93A1A1',
    borderRadius: '4px',
    shadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  form: {
    backgroundColor: '#FDF6E3',
    foreground: '#657B83',
    fontFamily: '"Consolas", "DejaVu Sans Mono", monospace',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: '#EEE8D5',
      border: '1px solid #93A1A1',
      borderRadius: '3px',
      foreground: '#586E75',
      hoverBackground: '#DDD6C1',
      padding: '4px 12px',
    },
    textInput: {
      background: '#FDF6E3',
      border: '1px solid #93A1A1',
      borderRadius: '3px',
      foreground: '#657B83',
      focusBorder: '2px solid #268BD2',
      padding: '4px 8px',
    },
    select: {
      background: '#FDF6E3',
      border: '1px solid #93A1A1',
      borderRadius: '3px',
      foreground: '#657B83',
      selectedBackground: '#268BD2',
      selectedForeground: '#FDF6E3',
    },
    checkRadio: {
      border: '1px solid #93A1A1',
      background: '#FDF6E3',
      checkedBackground: '#268BD2',
      borderRadius: '3px',
    },
    panel: {
      background: 'transparent',
      border: '1px solid #EEE8D5',
      borderRadius: '4px',
    },
    groupBox: {
      border: '1px solid #EEE8D5',
      borderRadius: '4px',
      foreground: '#586E75',
    },
    tabControl: {
      tabBackground: '#EEE8D5',
      tabActiveBackground: '#FDF6E3',
      tabBorder: '1px solid #93A1A1',
      tabBorderRadius: '4px 4px 0 0',
      tabForeground: '#93A1A1',
      tabActiveForeground: '#586E75',
      contentBackground: '#FDF6E3',
      contentBorder: '1px solid #EEE8D5',
    },
    dataGrid: {
      headerBackground: '#EEE8D5',
      headerForeground: '#586E75',
      headerBorder: '1px solid #93A1A1',
      rowBackground: '#FDF6E3',
      rowAlternateBackground: '#EEE8D5',
      rowForeground: '#657B83',
      border: '1px solid #93A1A1',
      borderRadius: '4px',
      selectedRowBackground: '#268BD2',
      selectedRowForeground: '#FDF6E3',
    },
    progressBar: {
      background: '#EEE8D5',
      fillBackground: '#268BD2',
      border: '1px solid #93A1A1',
      borderRadius: '3px',
    },
    menuStrip: {
      background: '#EEE8D5',
      foreground: '#586E75',
      border: '1px solid #DDD6C1',
      hoverBackground: '#DDD6C1',
      hoverForeground: '#586E75',
      activeBackground: '#268BD2',
    },
    toolStrip: {
      background: '#EEE8D5',
      foreground: '#586E75',
      border: '1px solid #DDD6C1',
      buttonHoverBackground: '#DDD6C1',
      separator: '#93A1A1',
    },
    statusStrip: {
      background: '#EEE8D5',
      foreground: '#93A1A1',
      border: '1px solid #DDD6C1',
    },
    scrollbar: {
      trackBackground: '#FDF6E3',
      thumbBackground: '#93A1A1',
      thumbHoverBackground: '#839496',
      width: 10,
    },
  },
  accent: {
    primary: '#268BD2',
    primaryHover: '#2176B5',
    primaryForeground: '#FDF6E3',
  },
  popup: {
    background: '#FDF6E3',
    border: '1px solid #93A1A1',
    shadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    borderRadius: '4px',
    hoverBackground: '#EEE8D5',
  },
};

export const sunsetGlowTheme: ThemeTokens = {
  id: 'sunset-glow',
  name: 'Sunset Glow',
  window: {
    titleBar: {
      background: 'linear-gradient(to right, #E65100, #AD1457)',
      foreground: '#FFFFFF',
      height: 34,
      font: '13px "Segoe UI", sans-serif',
      borderRadius: '10px 10px 0 0',
      controlButtonsPosition: 'right',
    },
    border: '1px solid rgba(230, 81, 0, 0.4)',
    borderRadius: '10px',
    shadow: '0 4px 20px rgba(230, 81, 0, 0.2), 0 0 12px rgba(173, 20, 87, 0.1)',
  },
  form: {
    backgroundColor: '#2A1B30',
    foreground: '#FFE0B2',
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: '13px',
  },
  controls: {
    button: {
      background: 'linear-gradient(135deg, #E65100, #F4511E)',
      border: '1px solid rgba(255, 109, 0, 0.4)',
      borderRadius: '8px',
      foreground: '#FFFFFF',
      hoverBackground: 'linear-gradient(135deg, #F4511E, #FF6D00)',
      padding: '4px 14px',
    },
    textInput: {
      background: '#3A2840',
      border: '1px solid rgba(255, 109, 0, 0.3)',
      borderRadius: '6px',
      foreground: '#FFE0B2',
      focusBorder: '2px solid #FF6D00',
      padding: '4px 8px',
    },
    select: {
      background: '#3A2840',
      border: '1px solid rgba(255, 109, 0, 0.3)',
      borderRadius: '6px',
      foreground: '#FFE0B2',
      selectedBackground: '#E65100',
      selectedForeground: '#FFFFFF',
    },
    checkRadio: {
      border: '1px solid rgba(255, 109, 0, 0.4)',
      background: '#3A2840',
      checkedBackground: '#FF6D00',
      borderRadius: '4px',
    },
    panel: {
      background: 'rgba(58, 40, 64, 0.6)',
      border: '1px solid rgba(255, 109, 0, 0.2)',
      borderRadius: '8px',
    },
    groupBox: {
      border: '1px solid rgba(255, 109, 0, 0.25)',
      borderRadius: '8px',
      foreground: '#FFAB40',
    },
    tabControl: {
      tabBackground: '#2A1B30',
      tabActiveBackground: '#3A2840',
      tabBorder: '1px solid rgba(255, 109, 0, 0.2)',
      tabBorderRadius: '8px 8px 0 0',
      tabForeground: '#BF8060',
      tabActiveForeground: '#FFAB40',
      contentBackground: '#3A2840',
      contentBorder: '1px solid rgba(255, 109, 0, 0.2)',
    },
    dataGrid: {
      headerBackground: '#3A2840',
      headerForeground: '#FFAB40',
      headerBorder: '1px solid rgba(255, 109, 0, 0.2)',
      rowBackground: '#2A1B30',
      rowAlternateBackground: '#322238',
      rowForeground: '#FFE0B2',
      border: '1px solid rgba(255, 109, 0, 0.2)',
      borderRadius: '8px',
      selectedRowBackground: '#E65100',
      selectedRowForeground: '#FFFFFF',
    },
    progressBar: {
      background: '#3A2840',
      fillBackground: 'linear-gradient(to right, #E65100, #FF6D00)',
      border: '1px solid rgba(255, 109, 0, 0.2)',
      borderRadius: '4px',
    },
    menuStrip: {
      background: '#221828',
      foreground: '#FFE0B2',
      border: '1px solid rgba(255, 109, 0, 0.15)',
      hoverBackground: 'rgba(230, 81, 0, 0.2)',
      hoverForeground: '#FFFFFF',
      activeBackground: '#E65100',
    },
    toolStrip: {
      background: '#2A1B30',
      foreground: '#FFAB40',
      border: '1px solid rgba(255, 109, 0, 0.15)',
      buttonHoverBackground: 'rgba(230, 81, 0, 0.2)',
      separator: 'rgba(255, 109, 0, 0.2)',
    },
    statusStrip: {
      background: '#221828',
      foreground: '#BF8060',
      border: '1px solid rgba(255, 109, 0, 0.15)',
    },
    scrollbar: {
      trackBackground: 'transparent',
      thumbBackground: 'rgba(255, 109, 0, 0.3)',
      thumbHoverBackground: 'rgba(255, 109, 0, 0.5)',
      width: 8,
    },
  },
  accent: {
    primary: '#FF6D00',
    primaryHover: '#E65100',
    primaryForeground: '#FFFFFF',
  },
  popup: {
    background: '#3A2840',
    border: '1px solid rgba(255, 109, 0, 0.3)',
    shadow: '0 8px 24px rgba(230, 81, 0, 0.2), 0 0 12px rgba(173, 20, 87, 0.1)',
    borderRadius: '8px',
    hoverBackground: 'rgba(230, 81, 0, 0.15)',
  },
};

const themeMap: Record<PresetThemeId, ThemeTokens> = {
  'arctic-frost': arcticFrostTheme,
  'autumn-harvest': autumnHarvestTheme,
  'cherry-blossom': cherryBlossomTheme,
  'dark-monokai': darkMonokaiTheme,
  'forest-green': forestGreenTheme,
  'macos-tahoe': macosTahoeTheme,
  'material-blue': materialBlueTheme,
  'ocean-breeze': oceanBreezeTheme,
  'retro-terminal': retroTerminalTheme,
  'solarized-light': solarizedLightTheme,
  'sunset-glow': sunsetGlowTheme,
  'ubuntu-2004': ubuntu2004Theme,
  'vibrant-neon': vibrantNeonTheme,
  'windows-xp': windowsXpTheme,
};

export const PRESET_THEME_IDS: PresetThemeId[] = [
  'arctic-frost',
  'autumn-harvest',
  'cherry-blossom',
  'dark-monokai',
  'forest-green',
  'macos-tahoe',
  'material-blue',
  'ocean-breeze',
  'retro-terminal',
  'solarized-light',
  'sunset-glow',
  'ubuntu-2004',
  'vibrant-neon',
  'windows-xp',
];

/** @deprecated Use PRESET_THEME_IDS */
export const THEME_IDS: PresetThemeId[] = PRESET_THEME_IDS;

export function isPresetTheme(id: string): id is PresetThemeId {
  return PRESET_THEME_IDS.includes(id as PresetThemeId);
}

export function getDefaultTheme(): ThemeTokens {
  return windowsXpTheme;
}

export function getPresetThemeById(id: PresetThemeId): ThemeTokens {
  return themeMap[id] ?? windowsXpTheme;
}

export function getThemeById(id: ThemeId | undefined): ThemeTokens {
  if (!id) return windowsXpTheme;
  return themeMap[id as PresetThemeId] ?? windowsXpTheme;
}
